- name: multi yaml
hosts: local
tasks:
- name: PLAY-01 TASK-01
 ansible.biltin.debug
 msg: "This is from PLAY-01 ANS TASK-01"

 - name: PLAY-02
  hosts: web
  tasks:
  - name: PLAY-02 TASK-01
    ansible.builtin.debug:
      msg: "This is from PLAY-02 and TASK-01"
      